# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cbba7b29cf7922b606ca1263ab10dd87d98fd0aa65c913daa5669fc5582593ecf9f9ec447c0a4435b709379338e34cf1f1003606b41a0793e9106cda80dbc41

test:
  secret_key_base: 3553446383f4bc6f73c755c0ce3f73440e61cc7030c9aa15b596c81af2404f606c8cff1cee8021ea7f9bae1e65f867412ed6249c14a73985bcd29885a1acea15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
